/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import javax.swing.JTextField;

import controller.ControllerCadastro;
/**
 *
 * @author unifysouza
 */
public class Cadastro extends javax.swing.JFrame {

    private ControllerCadastro controller;
    public Cadastro() {
        initComponents();
        controller = new ControllerCadastro(this);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeFood = new javax.swing.JLabel();
        LabelCriar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextNomeCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextUsuarioCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextSenhaCadastro = new javax.swing.JTextField();
        LabelPossuiconta = new javax.swing.JLabel();
        LabelPergunta = new javax.swing.JLabel();
        BotaoCadastro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeFood.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        NomeFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeFood.setText("FeiFood");

        LabelCriar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LabelCriar.setText("Crie Sua Conta!");

        jLabel1.setText("Nome:");

        TextNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeCadastroActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        LabelPossuiconta.setText("Já possui conta?");
        LabelPossuiconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPossuicontaMouseClicked(evt);
            }
        });

        LabelPergunta.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        LabelPergunta.setText("Fazer Login");
        LabelPergunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPerguntaMouseClicked(evt);
            }
        });

        BotaoCadastro.setText("Cadastrar");
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextUsuarioCadastro)
                            .addComponent(TextNomeCadastro)
                            .addComponent(TextSenhaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeFood, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCriar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(LabelPergunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelPossuiconta)
                            .addComponent(BotaoCadastro))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(NomeFood, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCriar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastro)
                .addGap(18, 18, 18)
                .addComponent(LabelPossuiconta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelPergunta)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeCadastroActionPerformed

    private void LabelPossuicontaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPossuicontaMouseClicked
        
    }//GEN-LAST:event_LabelPossuicontaMouseClicked

    private void LabelPerguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPerguntaMouseClicked
    Login telaDeLogin = new Login();
    telaDeLogin.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_LabelPerguntaMouseClicked

    public Cadastro(JTextField TextNomeCadastro, JTextField TextSenhaCadastro, JTextField TextUsuarioCadastro) throws HeadlessException {
        this.TextNomeCadastro = TextNomeCadastro;
        this.TextSenhaCadastro = TextSenhaCadastro;
        this.TextUsuarioCadastro = TextUsuarioCadastro;
    }

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
    
        controller.salvarUsuario();
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cadastro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCadastro;
    private javax.swing.JLabel LabelCriar;
    private javax.swing.JLabel LabelPergunta;
    private javax.swing.JLabel LabelPossuiconta;
    private javax.swing.JLabel NomeFood;
    private javax.swing.JTextField TextNomeCadastro;
    private javax.swing.JTextField TextSenhaCadastro;
    private javax.swing.JTextField TextUsuarioCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField getTextNomeCadastro() {
        return TextNomeCadastro;
}
    public javax.swing.JTextField getTextUsuarioCadastro() {
        return TextUsuarioCadastro;
}
    public javax.swing.JTextField getTextSenhaCadastro() {
        return TextSenhaCadastro;
}
}
